# Podcast Generation Configuration

# Google AI Studio settings
google_ai:
  model: "gemini-1.5-flash"
  api_key_env: "GOOGLE_AI_API_KEY"

# Voice configuration for speakers
# Using Chirp3-HD voices which support markup field for [pause] tags
# and custom_pronunciations API for phonetic tags
speakers:
  jordan:
    voice: "en-US-Chirp3-HD-Kore"  # Female voice (9/10 rating)
    speed: 0.95  # Slightly slower, more authoritative
    pitch: 0
    volume_gain_db: 0.0
    alternatives:  # Fallback voices in case of errors
      - "en-US-Chirp3-HD-Charon"
      - "en-US-Journey-D"
  alex:
    voice: "en-US-Chirp3-HD-Algieba"  # Male voice
    speed: 1.0  # Normal speed, energetic
    pitch: 0
    volume_gain_db: 0.0
    alternatives:  # Fallback voices in case of errors
      - "en-US-Chirp3-HD-Aoede"
      - "en-US-Journey-F"
  reel_presenter:
    voice: "en-US-Chirp3-HD-Aoede"  # Energetic voice for short-form reels
    speed: 1.15  # 15% faster for energy (reels need pace!)
    pitch: 0  # Chirp3-HD doesn't support pitch adjustment
    volume_gain_db: 0.0
    alternatives:  # Fallback voices in case of errors
      - "en-US-Chirp3-HD-Kore"
      - "en-US-Chirp3-HD-Charon"
  autonoe:
    voice: "en-US-Chirp3-HD-Autonoe"  # Clear, professional voice for educational lessons
    speed: 1.0  # Normal speed for natural conversational teaching (was 0.95, too slow/formal)
    pitch: 0  # Chirp3-HD doesn't support pitch adjustment
    volume_gain_db: 0.0
    alternatives:  # Fallback voices in case of errors
      - "en-US-Chirp3-HD-Kore"
      - "en-US-Chirp3-HD-Aoede"

# Audio settings
audio:
  sample_rate: 44100
  bitrate: "128k"
  format: "mp3"
  chunk_overlap_ms: 50  # Crossfade duration

# Chunking configuration (for two-person podcasts)
chunking:
  min_words: 80
  max_words: 150
  target_words: 100  # Ideal chunk size for dialogue
  target_duration_seconds: 45
  max_duration_seconds: 90

# Lesson chunking configuration (for single-speaker educational content)
# Lessons need longer chunks to avoid breaking mid-concept
lesson_chunking:
  min_words: 150  # Longer to keep complete thoughts together
  max_words: 300  # Allow full explanations without artificial breaks
  target_words: 200  # ~60-75 seconds of natural speech
  target_duration_seconds: 60
  max_duration_seconds: 120
  # Prefer breaking on natural boundaries:
  # - After [pause long] tags (major transitions)
  # - After complete explanations
  # - Between teaching sections
  # Avoid breaking mid-analogy, mid-example, or mid-list

# Paths
paths:
  cache_dir: "cache"
  chunks_dir: "cache/chunks"
  output_dir: "output"
  manifest_file: "cache/manifest.json"

# Processing settings
processing:
  max_retries: 3
  retry_delay: 1.0
  rate_limit_delay: 0.5